<?php

/**
 * @file
 * Contains poll_variants.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function poll_variants_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the poll_variants module.
    case 'help.page.poll_variants':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Poll variants') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function poll_variants_theme() {
  return [
    'poll_variants' => [
      'render element' => 'children',
    ],
  ];
}
