social_auth_telegram.settings:
  type: config_object
  label: 'Social Auth Telegram settings'
  mapping:
    widget_code:
      type: string
      label: 'Telegram widget code'
    token:
      type: string
      label: 'App token'
    email_domain:
      type: string
      label: 'Email domain for generating bogus email addresses. Email does not provide Telegram.'
