<?php

/**
 * @file
 * Contains freedom_edms.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function freedom_edms_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the freedom_edms module.
    case 'help.page.freedom_edms':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Freedom Electronic document management system') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function freedom_edms_theme() {
  return [
    'freedom_edms' => [
      'render element' => 'children',
    ],
  ];
}
