widget_code: '<script async src="https://telegram.org/js/telegram-widget.js?14" data-telegram-login="freedom_pdd_local_bot" data-size="large" data-userpic="false" data-auth-url="/user/login/telegram/callback" data-request-access="write"></script>'
token: '1527898966:AAHq3-0g0zESTC3KVoWePJf531Um7gfcYb0'
email_domain: freedom.loc.ti-work.ru
