<?php

/**
 * @file
 * Contains freedom_views.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function freedom_views_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the freedom_views module.
    case 'help.page.freedom_views':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Views utils') . '</p>';
      return $output;

    default:
  }
}
