<?php

/**
 * @file
 * Contains gpb_og.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gpb_og_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gpb_og module.
    case 'help.page.gpb_og':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

function gpb_og_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!isset($form['og_audience'])) {
    return;
  }
//  $form['og_audience']['#access'] = FALSE;
}
