<?php

/**
 * @file
 * Contains gpb_og.module.
 */

use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gpb_og_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gpb_og module.
    case 'help.page.gpb_og':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

function gpb_og_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!isset($form['og_audience'])) {
    return;
  }
  //  $form['og_audience']['#access'] = FALSE;
}

/**
 * Implements hook_views_data().
 */
function gpb_og_views_data_alter(array &$data) {

  $test = $data['node_field_data'];
  $n = 0;
  $data['node_field_data']['og_membership']['title'] = t('Og Node membership');
  $data['node_field_data']['og_membership']['relationship'] = [
    'base' => 'og_membership',
    'base field' => 'entity_id',
    'field' => 'nid',
    'group' => t('Organic group'),
    'id' => 'standard',
    'label' => t('Og Node membership'),
    'extra' => [
      [
        'field' => 'entity_type',
        'value' => 'node',
      ],
      [
        'field' => 'entity_bundle',
        'left_field' => 'type',
      ],
    ],

  ];
  //  $data['og_membership'] = [
  //    'table' => [
  //      'group' => t('Og'),
  //      'base' => [
  //        'field' => 'id',
  //        'title' => t('Member'),
  //        'help' => t('Contains a list of Did this help? entries.'),
  //      ],
  //    ],
  //  ];
}

function gpb_og_preprocess_field_multiple_value_form(&$variables) {
  $element = $variables['element'];

  if ($field = NestedArray::getValue($variables, ['element', 0, '#field_mode'])) {
    unset($variables['table']);

    $element = $variables['element'];
    $variables['label'] = $element['#title'];
    $variables['items'] = [];
    foreach (Element::children($element) as $key) {
      if ($key === 'add_more') {
        continue;
      }
      $variables['items'][] = $element[$key]['target_id'];
    }

  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function gpb_og_theme_suggestions_field_multiple_value_form(array $variables) {
  $suggestions = [];
  $element = $variables['element'];
  if (isset($element[0]) && isset($element[0]['#field_mode'])) {
    $field = $element[0];
    $field_mode = $field['#field_mode'];
    $suggestions[] = 'field_multiple_value_form__' . $field_mode;

  }

  return $suggestions;
}
