<?php

namespace Drupal\gpb_og\Plugin\Menu;

use Drupal\Core\Menu\MenuLinkDefault;
use Drupal\Core\Menu\StaticMenuLinkOverridesInterface;
use Drupal\Core\Routing\RedirectDestinationInterface;
use Drupal\og\OgContextInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

class OgContentLink extends MenuLinkDefault {

  /**
   * @var \Drupal\Core\Routing\RedirectDestinationInterface
   */
  private RedirectDestinationInterface $redirectDestination;

  /**
   * @var \Drupal\og\OgContextInterface
   */
  private OgContextInterface $ogContext;

  public function __construct(array $configuration,
                              $plugin_id,
                              $plugin_definition,
                              StaticMenuLinkOverridesInterface $static_override,
                              OgContextInterface $ogContext) {
    parent::__construct($configuration, $plugin_id, $plugin_definition, $static_override);
    $this->ogContext = $ogContext;
  }

  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    return new static(
      $configuration,
      $plugin_id,
      $plugin_definition,
      $container->get('menu_link.static.overrides'),
      $container->get('og.context')

    );
  }

  public function getOptions() {
    $options= parent::getOptions(); // TODO: Change the autogenerated stub
    if ($group = $this->ogContext->getGroup()) {
      /** @var $group \Drupal\Core\Entity\ContentEntityInterface   */
      $options['query']['og-type'] = $group->getEntityTypeId();
      $options['query']['og-id'] = $group->id();
    }
    return $options;
  }

  public function getRouteParameters() {
    $parameters = parent::getRouteParameters(); // TODO: Change the autogenerated stub
    if (!isset($parameters['group']) || empty($parameters['group'])) {
      if ($group = $this->ogContext->getGroup()) {
        $parameters['group'] = $group->id();
      } else {
        $parameters['group'] = 0;
      }
    }
    return $parameters;
  }

}
