<?php

namespace Drupal\gpb_og\Plugin\Menu;

use Drupal;
use Drupal\Core\Menu\MenuLinkDefault;
use Drupal\Core\Menu\StaticMenuLinkOverridesInterface;
use Drupal\Core\Routing\RedirectDestinationInterface;
use Drupal\og\OgContextInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use function array_filter;
use function explode;

class OgContentLink extends MenuLinkDefault {

  /**
   * @var \Drupal\Core\Routing\RedirectDestinationInterface
   */
  private RedirectDestinationInterface $redirectDestination;

  /**
   * @var \Drupal\og\OgContextInterface
   */
  private OgContextInterface $ogContext;

  public function __construct(array $configuration,
                              $plugin_id,
                              $plugin_definition,
                              StaticMenuLinkOverridesInterface $static_override,
                              OgContextInterface $ogContext) {
    parent::__construct($configuration, $plugin_id, $plugin_definition, $static_override);
    $this->ogContext = $ogContext;
  }

  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    return new static(
      $configuration,
      $plugin_id,
      $plugin_definition,
      $container->get('menu_link.static.overrides'),
      $container->get('og.context')

    );
  }

  public function getRouteParameters() {
    $parameters = parent::getRouteParameters(); // TODO: Change the autogenerated stub
    $routeMatch = Drupal::routeMatch();
    $route = $routeMatch->getRouteObject();
    $path = $route->getPath();
    $path_parts = array_filter(explode('/', $path));
    
    
    if (reset($path_parts) === 'project') {
      if ($group_id = $routeMatch->getParameter('group')) {
        $parameters['group'] = $group_id;
      } else {
        $parameters['group'] = 0;
      }
    }
    return $parameters;
  }

}
